# Generated by Django 4.1 on 2022-09-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constant_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplementaryinsurance',
            name='name',
        ),
    ]
