# Generated by Django 4.1 on 2022-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='room_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
