# Generated by Django 4.1 on 2022-12-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_alter_visit_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('paraclinic', 'Paraclinic')], default='paraclinic', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.doctorprescription')),
            ],
        ),
    ]
