# Generated by Django 4.1 on 2022-12-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_laboratoryprescription_delivery_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratoryprescription',
            old_name='doctor',
            new_name='doctor_name',
        ),
    ]
