# Generated by Django 4.1 on 2022-12-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_rename_doctor_laboratoryprescription_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=40, null=True)),
                ('insurance', models.BooleanField(default=False)),
                ('sup_insurance', models.BooleanField(default=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratoryprescription')),
            ],
        ),
    ]
