# Generated by Django 4.1 on 2022-12-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_testprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryprescription',
            name='time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='laboratory.laboratoryprescription'),
        ),
    ]
