# Generated by Django 4.1 on 2022-12-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_description'),
        ('laboratory', '0005_laboratoryprescription_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryprescription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_prescription', to='payment.payment'),
        ),
    ]
