# Generated by Django 4.1 on 2022-12-13 11:53

from django.db import migrations, models
import django.db.models.deletion
import laboratory.models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_laboratoryprescription_selected_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryResultPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=laboratory.models.img_upload_path_generator)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratoryprescription')),
            ],
        ),
    ]
