# Generated by Django 4.1 on 2022-09-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth_jalali',
        ),
    ]
