# Generated by Django 4.1 on 2022-09-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant_data', '0002_remove_city_name_remove_supplementaryinsurance_name'),
        ('patient', '0002_remove_patient_date_of_birth_jalali'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constant_data.city'),
        ),
        migrations.AddField(
            model_name='patient',
            name='supplementary_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant_data.supplementaryinsurance'),
        ),
    ]
