# Generated by Django 4.1 on 2022-10-02 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.Point(0,0), srid=4326),
            preserve_default=False,
        ),
    ]
