# Generated by Django 4.1 on 2022-11-21 12:18

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=support.models.img_upload_path_generator),
        ),
    ]
