# Generated by Django 4.1 on 2022-10-04 09:51

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('constant_data', '0002_remove_city_name_remove_supplementaryinsurance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField(max_length=255)),
                ('open_hours', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('degree', models.CharField(choices=[('general_doctor', 'General Doctor'), ('full_doctor', 'Full Doctor'), ('specialized_doctor', 'Specialized doctor')], max_length=20)),
                ('medicalCode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=doctor.models._doctor_img_upload_path_generator)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.office')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constant_data.city')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.department')),
            ],
        ),
    ]
