# Generated by Django 4.1 on 2022-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_medicalcode_doctor_medical_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
