# Generated by Django 4.1 on 2022-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_department_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='amount',
            field=models.IntegerField(default=500000),
        ),
    ]
