# Generated by Django 4.1 on 2022-11-28 12:02

from django.db import migrations, models
import django.db.models.deletion
import pharmacy.models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacyprescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprescription',
            name='pharmacy_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprescription',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientPrescriptionPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pharmacy.models.img_upload_path_generator)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyprescription')),
            ],
        ),
    ]
