# Generated by Django 4.1 on 2022-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_pharmacyprescription_pharmacy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprescription',
            name='delivery_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
