# Generated by Django 4.1 on 2022-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_pharmacyprescription_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprescription',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprescription',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
