# Generated by Django 4.1 on 2022-11-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_description'),
        ('pharmacy', '0006_pharmacyprescription_day_pharmacyprescription_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprescription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
